version: '2'
services:
    jhipdemoapp-app:
        image: jhipdemoapp
        external_links:
            - jhipdemoapp-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipDemoApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipdemoapp-mongodb:
        extends:
            file: mongodb.yml
            service: jhipdemoapp-mongodb
