version: '2'
services:
    jhipdemoapp-mongodb:
        container_name: jhipdemoapp-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jhipDemoApp/mongodb/:/data/db/
